- name: install python packages (python)
  apt:
    name: ["python3-pip", "python3-dev", "python3-psycopg2", "python3-venv"]
    state: present

- name: install postgres packages (postgres)
  tags: postgres, database
  apt:
    name: ["postgresql", "postgresql-contrib", "libpq-dev"]
    state: present

- name: install nginx (server)
  tags: nginx, server
  apt:
    name: nginx
    state: present

- name: install npm and rsync
  tags: npm, rsync
  apt:
    name: ["npm", "rsync"]
    state: present
# install packages needed for deployment (edit as needed)
